### ISSUE TITLE
Support for Certificate Transparency as enhancement

### ISSUE THREAD

**Issue by scottallan** [canada-ca/CATS-STAE#13]
https://github.com/canada-ca/CATS-STAE/blob/34f73e2598c9ac47b4e7c11fdd7a2115ea0e44e2/docs/saml2cred.html#L1127

4.2.2.1 states
"Deployments MUST perform path validation and check the revocation status of X.509 certificates used for TLS server authentication."

We should consider enforcing that Deployments include SCT (Signed Certificate Timestamps) in their TLS Certs utilizing the X.509v3 Extension (OID 1.3.6.1.4.1.11129.2.4.3)
see:
https://www.certificate-transparency.org/ 
https://tools.ietf.org/html/rfc6962

**Comment by harrdou** [comment]
Added the requirement to meet the Apple and Chromium CT policies.
