### ISSUE TITLE
The HTTP-Redirect binding [SAML2Bind] MUST be used for the transmission of <samlp:LogoutResponse> messages.

### ISSUE THREAD

**Issue by scottallan** [canada-ca/CATS-STAE#14]
https://github.com/canada-ca/CATS-STAE/blob/34f73e2598c9ac47b4e7c11fdd7a2115ea0e44e2/docs/saml2cred.html#L2887

Is this correct?  wouldn't the response be over backchannel for those SPs that support SOAP logout binding?

**Comment by harrdou** [comment]
This is for the "result" transmission back to the SP that initiated the logout, not for propagation to other SPs which would be done using a <code>&lt;samlp:LogoutRequest&gt;</code> message.
