### ISSUE TITLE
Can i get some direction where the CATSv2IDPAttributeMapper might be

### ISSUE THREAD

**Issue by ricardosaracino** [canada-ca/CATS-STAE#17]
Any idea where i might acquire the CATSv2IDPAttributeMapper for OpenAM.

```xml
<Attribute name="idpAttributeMapper">
    <Value>ca.gc.ssc.cats.CATSv2IDPAttributeMapper</Value>
</Attribute>
```

**Comment by harrdou** [comment]
Some day I may get around to creating an OpenAM fork that includes all these little CATS patches.

For now I've put this one here...

https://gist.github.com/harrdou/1d366a23a50c33f5b401def8eef223b8
