### ISSUE TITLE
[ODP-RP04] typo

### ISSUE THREAD

**Issue by chrisgolle** [canada-ca/CATS-STAE#27]
There is a small typo in ODP-RP04, "subequent"
> RP implementations MUST include the claims parameter in all authentication requests that, as a minimum, requests the locale claim. The claims parameter SHOULD request that the locale claim be returned in the ID token. RP applications MUST examine the value of the returned locale claim to determine if the user changed their preferred official language while interacting with the OP, in which case the RP application MUST display all **subequent** content in the newly selected language.

**Comment by harrdou** [comment]
Thanks Chris. I've fixed the typo.

I'm hoping to remove the requirement for the RP to pass the claims request parameter just to ask for locale. The OP should pass locale in the id token by default.
